# http://travis-ci.org/#!/bollwyvl/cookiecutter-ipython-widget
language: python
python:
    - 3.4
    - 2.7
    - 3.3
env:
    - GROUP=js
    - GROUP=
before_install:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # Pierre Carrier's PPA for PhantomJS and CasperJS
    - time sudo add-apt-repository -y ppa:pcarrier/ppa
    - time sudo apt-get update
    - time sudo apt-get install pandoc casperjs libzmq3-dev
    # pin tornado < 4 for js tests while phantom is on super old webkit
    - if [[ $GROUP == 'js' ]]; then pip install 'tornado<4'; fi
    - time pip install -r requirements.txt
install:
    - time python setup.py install -q 
script:
    - cd /tmp; cookiecutter ~/ --no-input; cd IPythonCustomWidget; python tests/test_widgets.py

matrix:
    exclude:
        - python: 3.3
          env: GROUP=js
