# http://travis-ci.org/#!/bollwyvl/cookiecutter-ipython-widget
language: python
python:
  - 3.4
  - 2.7
  - 3.3
before_install:
  - npm install -g casperjs
install:
  - time pip install -r requirements.txt
script:
  - cookiecutter . --no-input
  - cd IPythonCustomWidget
  - python setup.py develop
  - python tests/test_widgets.py
